Repository ambianic/ambianic-ui, pull requests merged in 2020-04, with the labels that each got.

#309 fix: dependency tree
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
Labels: size/XS

#321 fix: netlify precaching issue with pwa
  vue.config.js
Labels: size/XS

#322 fix: Show version info in About page
  src/store/index.js
  src/views/About.vue
  src/views/EdgeConnect.vue
Labels: size/S

#323 fix: link app bar logo icon to about page, closes #301
  src/components/AppFrame.vue
Labels: size/XS

#324 fix: installed pwa does not pick up new version, closes #298
  src/components/AppFrame.vue
  src/components/UpdateNotification.vue
  src/registerServiceWorker.js
  src/store/index.js
  src/store/mutation-types.js
  src/views/Home.vue
Labels: size/M

#333 fix: codecov report upload
  .github/workflows/nodejs.yml
Labels: size/XS

#334 fix: codecov report upload
  .github/workflows/nodejs.yml
Labels: size/XS

#335 fix: coverage report upload
  .github/workflows/nodejs.yml
  .releaserc
  package-lock.json
  package.json
Labels: size/S

#336 fix: codecov commit comments
  .github/workflows/nodejs.yml
  codecov.yml
Labels: size/M

#337 build: code cov
  .github/workflows/nodejs.yml
Labels: size/XS

#339 feature: adds ui-tests
  cypress/integration/ambianic-tests/home.spec.js
Labels: size/M

#341 Corrected typos on three pages in /views/ folder
  src/views/About.vue
  src/views/Feedback.vue
  src/views/Help.vue
Labels: size/XS
