Repository ambianic/ambianic-ui, pull requests merged in 2020-05, with the labels that each got.

#348 Creates lighthouse ci
  .github/lighthouse/budget.json
  .github/lighthouse/lighthouserc.json
  .github/workflows/lighthouse.yml
Labels: size/L

#367 build: add lighthouse PWA check before release
  .github/lighthouse/budget.json
  .github/lighthouse/lighthouserc-netlify-preview.json
  .github/lighthouse/lighthouserc-netlify-prod.json
  .github/lighthouse/lighthouserc-static-dist-dir.yml
  .github/lighthouse/lighthouserc.json
  .github/workflows/lighthouse.yml
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  public/index.html
  src/main.js
Labels: size/L

#371 perf: various optimizations from Nasr
  .github/workflows/lighthouse.yml
  cypress/integration/ambianic-tests/about.spec.js
  cypress/integration/ambianic-tests/feedback.spec.js
  cypress/integration/ambianic-tests/help.spec.js
  package-lock.json
  package.json
  src/App.vue
  src/components/AppFrame.vue
  src/components/FooterInfo.vue
  src/components/NavBar.vue
  src/components/TodoItem.vue
  src/components/shared/Banner.vue
  src/components/shared/Button.vue
  src/components/shared/ListItem.vue
  src/router/index.js
  src/views/About.vue
  src/views/EdgeConnect.vue
  src/views/Feedback.vue
  src/views/Flows.vue
  src/views/Help.vue
  src/views/Home.vue
  src/views/People.vue
  src/views/Settings.vue
  src/views/Timeline.vue
  vue.config.js
Labels: size/XXL

#373 fix: precache issue with netlify.toml
  vue.config.js
Labels: size/S

#379 build: fix codecov flags
  .github/workflows/lighthouse.yml
  .github/workflows/nodejs.yml
Labels: size/XS
