Repository ambianic/ambianic-ui, pull requests merged in 2021-03, with the labels that each got.

#586 feat: added timeline icon to navbar
  cypress/integration/ambianic-tests/navbar.spec.js
  src/components/NavBar.vue
  tests/unit/components/navbar/navbar.spec.js
Labels: size/M

#593 fix: silent console error when trying to draw a detection box for falls
  package-lock.json
  src/components/DetectionBoxes.vue
  src/views/Timeline.vue
Labels: size/XS

#597 build: fix gitpod hanging issue [skip ci]
  .gitpod.Dockerfile
  .gitpod.yml
Labels: size/XS

#599 build: fix gitpod hang [skip ci]
  .gitpod.yml
  package-lock.json
Labels: size/S
