Repository ambianic/ambianic-ui, pull requests merged in 2021-08, with the labels that each got.

#696 build: update github actions versions
  .github/lighthouse/lighthouserc-netlify-preview.json
  .github/lighthouse/lighthouserc-netlify-prod.json
  .github/workflows/lighthouse.yml
  .github/workflows/main.yml
  .gitpod.yml
  README.md
  cypress/integration/ambianic-tests/about.spec.js
  cypress/integration/ambianic-tests/actions.spec.js
  cypress/integration/ambianic-tests/home.spec.js
  cypress/integration/ambianic-tests/navbar.spec.js
  docs/img/ambianic-ui-dekstop-screenshot.png
  docs/img/ambianic-ui-mobile-screenshot.png
  more
  netlify.toml
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.vue
  src/components/AppFrame.vue
  src/components/DetectionBoxes.vue
  src/components/NavBar.vue
  src/main.js
  src/store/index.js
  src/store/pnp.js
  src/views/About.vue
  src/views/Feedback.vue
  src/views/Help.vue
  src/views/Home.vue
  src/views/Onboarding.vue
  src/views/Settings.vue
  src/views/Timeline.vue
  tests/unit/components/navbar/navbar.spec.js
  tests/unit/components/settings/settings.spec.js
  tests/unit/components/timeline/timeline.spec.js
  tests/unit/store/pnp-actions.spec.js
  tests/unit/store/pnp-mutations.spec.js
  vue.config.js
Labels: size/XXL

#682 ci: added husky to run precommit hook
  .github/workflows/main.yml
  .gitpod.yml
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  src/components/DetectionBoxes.vue
  src/store/pnp.js
  tests/unit/components/settings/settings.spec.js
  tests/unit/store/pnp-actions.spec.js
  tests/unit/store/pnp-mutations.spec.js
  yarn.lock
Labels: size/XXL

#699 feat: convenient copy paste button for edge device ID
  .github/workflows/main.yml
  cypress/.eslintrc
  cypress/integration/ambianic-tests/about.spec.js
  cypress/integration/ambianic-tests/actions.spec.js
  cypress/integration/ambianic-tests/feedback.spec.js
  cypress/integration/ambianic-tests/help.spec.js
  cypress/integration/ambianic-tests/home.spec.js
  cypress/integration/ambianic-tests/navbar.spec.js
  cypress/integration/ambianic-tests/settings.spec.js
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  package-lock.json
  package.json
  src/components/shared/ListItem.vue
  src/views/Settings.vue
  tests/unit/components/eventicon.spec.js
  tests/unit/components/navbar.spec.js
  tests/unit/components/settings/settings.spec.js
  tests/unit/views/settings.spec.js
  tests/unit/views/timeline.spec.js
Labels: size/XXL

#582 feat: fetch of edge version with a fallback option
  .gitignore
  cypress/integration/ambianic-tests/about.spec.js
  cypress/integration/ambianic-tests/settings.spec.js
  package-lock.json
  package.json
  src/components/shared/ListItem.vue
  src/main.js
  src/remote/edgeAPI.js
  src/store/edge-device.js
  src/store/index.js
  src/store/mutation-types.js
  src/views/About.vue
  src/views/Home.vue
  src/views/Settings.vue
  src/views/Timeline.vue
  tests/unit/components/about.spec.js
  tests/unit/remote/edgeAPI.spec.js
  tests/unit/store/edgeDevice.spec.js
  tests/unit/store/pnp-actions.spec.js
  tests/unit/views/settings.spec.js
  yarn.lock
Labels: size/XL

#707 fix: install wizard bugs
  cypress.json
  cypress/integration/ambianic-tests/onboarding.spec.js
  cypress/integration/ambianic-tests/onboardingpwa.spec.js
  cypress/integration/ambianic-tests/timeline.spec.js
  cypress/plugins/index.js
  package-lock.json
  package.json
  src/main.js
  src/views/Home.vue
  src/views/Onboarding.vue
Labels: size/L
