Repository ambianic/ambianic-ui, pull requests merged in 2021-01, with the labels that each got.

#445 feat: change theme colors
  src/App.vue
  src/components/NavBar.vue
  src/components/shared/Banner.vue
  src/components/shared/Button.vue
  src/components/shared/ListItem.vue
  src/plugins/vuetify.js
  src/views/About.vue
  src/views/Feedback.vue
  src/views/Help.vue
  src/views/Settings.vue
  src/views/Timeline.vue
Labels: size/M

#486 feat: timeline refresh, closes #413
  .gitpod.yml
  .theia/settings.json
  package-lock.json
  src/views/Timeline.vue
Labels: size/L

#487 fix: simultaneous top/bottom timeline update spinner
  package-lock.json
  package.json
  src/views/Timeline.vue
Labels: size/M

#496 Adjust return users flow to navigate to timeline
  cypress/integration/ambianic-tests/about.spec.js
  cypress/integration/ambianic-tests/home.spec.js
  cypress/integration/ambianic-tests/onboarding.spec.js
  src/main.js
  src/views/Home.vue
  yarn.lock
Labels: size/S
